import { Vacuum } from "./Vacuum";

export let w1 = new Vacuum(
  "Dyson Cyclone V10",
  5190,
  "url(../assets/Dysoncyclonev10_productpage.png)",
  "<img src='../assets/Sladdlös-Dyson-Cyclone-V10.png' alt='Bild på en dammsugaren' width='200' height='250'/>",
  "<h2>Dyson Cyclone V10</h2>",
  "<span> Byggt för djup rengöring, överallt. Upp till 60 minuter körtid.</span>",
  "<h1>Dyson Cyclone V10</h1>",
  "<h1>Oslagbar prestanda</h1>",
  "Dyson Cyclone V10 Absolute kommer med upp till 60 minuters kraftfull bibehållen sugförmåga. Den 40% större behållaren betyder också färre avbrott.",
  "<h1>Avancerad filtrering</h1>",
  "Avancerad filtrering säkerställer att dammsugaren släpper ut renare luft och tömningssystemet 'point and shoot' möjliggör en mer hygienisk metod för att tömma behållaren. Inkluderar åtta verktyg och tillbehör för grundlig rengöring var som helst i hemmet.",
  " Läs mer <i class='fas fa-info-circle'></i>",
  " Lägg till i varukorg <i class='fas fa-cart-plus'></i>",
  1,
  "wireless",
  1,
  "",
  false
);
export let w2 = new Vacuum(
  "Dyson Outsize",
  8290,
  "url(../assets/Dysoncyclonev10_productpage.png)",
  "<img src='../assets/Sladdlös-Dyson-Outsize.png' alt='Bild på en dammsugaren' width='200' height='250'/>",
  "<h2>Dyson Outsize</h2>",
  "<span> Byggt för djup rengöring, överallt. Upp till 60 minuter körtid.</span>",
  "<h1>Dyson Outsize</h1>",
  "<h1>Oslagbar prestanda</h1>",
  "Dyson Cyclone V10 Absolute kommer med upp till 60 minuters kraftfull bibehållen sugförmåga. Den 40% större behållaren betyder också färre avbrott.",
  "<h1>Avancerad filtrering</h1>",
  "Avancerad filtrering säkerställer att dammsugaren släpper ut renare luft och tömningssystemet 'point and shoot' möjliggör en mer hygienisk metod för att tömma behållaren. Inkluderar åtta verktyg och tillbehör för grundlig rengöring var som helst i hemmet.",
  " Läs mer <i class='fas fa-info-circle'></i>",
  " Lägg till i varukorg <i class='fas fa-cart-plus'></i>",
  2,
  "wireless",
  1,
  "",
  false
);

export let w3 = new Vacuum(
  "Dyson V12 detect slim Complete",
  7190,
  "url(../assets/Dysoncyclonev10_productpage.png)",
  "<img src='../assets/Sladdlös-Dyson-V12-detect-slim-Complete.png' alt='Bild på en dammsugaren' width='200' height='250'/>",
  "<h2>Dyson V12 detect slim Complete</h2>",
  "<span> Byggt för djup rengöring, överallt. Upp till 60 minuter körtid.</span>",
  "<h1>Dyson V12 detect slim Complete</h1>",
  "<h1>Oslagbar prestanda</h1>",
  "Dyson Cyclone V10 Absolute kommer med upp till 60 minuters kraftfull bibehållen sugförmåga. Den 40% större behållaren betyder också färre avbrott.",
  "<h1>Avancerad filtrering</h1>",
  "Avancerad filtrering säkerställer att dammsugaren släpper ut renare luft och tömningssystemet 'point and shoot' möjliggör en mer hygienisk metod för att tömma behållaren. Inkluderar åtta verktyg och tillbehör för grundlig rengöring var som helst i hemmet.",
  " Läs mer <i class='fas fa-info-circle'></i>",
  " Lägg till i varukorg <i class='fas fa-cart-plus'></i>",
  3,
  "wireless",
  1,
  "",
  false
);

export let w4 = new Vacuum(
  "Dyson V15 Detect Absolute",
  7190,
  "url(../assets/Dysoncyclonev10_productpage.png)",
  "<img src='../assets/Sladdlös-Dyson-V15-Detect-Absolute-logo.png' alt='Bild på en dammsugaren' width='200' height='250'/>",
  "<h2>Dyson V15 Detect Absolute</h2>",
  "<span> Byggt för djup rengöring, överallt. Upp till 60 minuter körtid.</span>",
  "<h1>Dyson V15 Detect Absolute</h1>",
  "<h1>Oslagbar prestanda</h1>",
  "Dyson Cyclone V10 Absolute kommer med upp till 60 minuters kraftfull bibehållen sugförmåga. Den 40% större behållaren betyder också färre avbrott.",
  "<h1>Avancerad filtrering</h1>",
  "Avancerad filtrering säkerställer att dammsugaren släpper ut renare luft och tömningssystemet 'point and shoot' möjliggör en mer hygienisk metod för att tömma behållaren. Inkluderar åtta verktyg och tillbehör för grundlig rengöring var som helst i hemmet.",
  " Läs mer <i class='fas fa-info-circle'></i>",
  " Lägg till i varukorg <i class='fas fa-cart-plus'></i>",
  4,
  "wireless",
  1,
  "",
  false
);

export let p1 = new Vacuum(
  "Dyson Big Ball Multi Floor",
  3190,
  "url(../assets/Dysoncyclonev10_productpage.png)",
  "<img src='../assets/Kraftfull-Dyson-Big-Ball-Multi-Floor-2.png' alt='Bild på en dammsugaren' width='200' height='250'/>",
  "<h2>Dyson Big Ball Multi Floor</h2>",
  "<span> Byggt för djup rengöring, överallt. Upp till 60 minuter körtid.</span>",
  "<h1>Dyson Big Ball Multi Floor</h1>",
  "<h1>Oslagbar prestanda</h1>",
  "Dyson Cyclone V10 Absolute kommer med upp till 60 minuters kraftfull bibehållen sugförmåga. Den 40% större behållaren betyder också färre avbrott.",
  "<h1>Avancerad filtrering</h1>",
  "Avancerad filtrering säkerställer att dammsugaren släpper ut renare luft och tömningssystemet 'point and shoot' möjliggör en mer hygienisk metod för att tömma behållaren. Inkluderar åtta verktyg och tillbehör för grundlig rengöring var som helst i hemmet.",
  " Läs mer <i class='fas fa-info-circle'></i>",
  " Lägg till i varukorg <i class='fas fa-cart-plus'></i>",
  5,
  "powerfull",
  1,
  "",
  false
);

export let p2 = new Vacuum(
  "Dyson Cinetic Big Ball Absolute",
  4190,
  "url(../assets/Dysoncyclonev10_productpage.png)",
  "<img src='../assets/Kraftfull-Dyson-Cinetic-Big-Ball-Absolute-2.png' alt='Bild på en dammsugaren' width='200' height='250'/>",
  "<h2>Dyson Cinetic Big Ball Absolute</h2>",
  "<span> Byggt för djup rengöring, överallt. Upp till 60 minuter körtid.</span>",
  "<h1>Dyson Cinetic Big Ball Absolute</h1>",
  "<h1>Oslagbar prestanda</h1>",
  "Dyson Cyclone V10 Absolute kommer med upp till 60 minuters kraftfull bibehållen sugförmåga. Den 40% större behållaren betyder också färre avbrott.",
  "<h1>Avancerad filtrering</h1>",
  "Avancerad filtrering säkerställer att dammsugaren släpper ut renare luft och tömningssystemet 'point and shoot' möjliggör en mer hygienisk metod för att tömma behållaren. Inkluderar åtta verktyg och tillbehör för grundlig rengöring var som helst i hemmet.",
  " Läs mer <i class='fas fa-info-circle'></i>",
  " Lägg till i varukorg <i class='fas fa-cart-plus'></i>",
  6,
  "powerfull",
  1,
  "",
  false
);

export let p3 = new Vacuum(
  "Dyson Cinetic Big Ball Animal Pro 1",
  4190,
  "url(../assets/Dysoncyclonev10_productpage.png)",
  "<img src='../assets/Kraftfull-Dyson-Cinetic-Big-Ball-Animal-Pro-1.png' alt='Bild på en dammsugaren' width='200' height='250'/>",
  "<h2>Dyson Cinetic Big Ball Animal Pro 1</h2>",
  "<span>Byggt för djup rengöring, överallt. Upp till 60 minuter körtid.</span>",
  "<h1>Dyson Cinetic Big Ball Animal Pro 1</h1>",
  "<h1>Oslagbar prestanda</h1>",
  "Dyson Cyclone V10 Absolute kommer med upp till 60 minuters kraftfull bibehållen sugförmåga. Den 40% större behållaren betyder också färre avbrott.",
  "<h1>Avancerad filtrering</h1>",
  "Avancerad filtrering säkerställer att dammsugaren släpper ut renare luft och tömningssystemet 'point and shoot' möjliggör en mer hygienisk metod för att tömma behållaren. Inkluderar åtta verktyg och tillbehör för grundlig rengöring var som helst i hemmet.",
  " Läs mer <i class='fas fa-info-circle'></i>",
  " Lägg till i varukorg <i class='fas fa-cart-plus'></i>",
  7,
  "powerfull",
  1,
  "",
  false
);

export let p4 = new Vacuum(
  "Dyson Cinetic Big Ball Animal Pro 2",
  5190,
  "url(../assets/Dysoncyclonev10_productpage.png)",
  "<img src='../assets/Kraftfull-Dyson-Cinetic-Big-Ball-Animal-Pro-2.png' alt='Bild på en dammsugaren' width='200' height='250'/>",
  "<h2>Dyson Cinetic Big Ball Animal Pro 2</h2>",
  "<span>Byggt för djup rengöring, överallt. Upp till 60 minuter körtid.</span>",
  "<h1>Dyson Cinetic Big Ball Animal Pro 2</h1>",
  "<h1>Oslagbar prestanda</h1>",
  "Dyson Cyclone V10 Absolute kommer med upp till 60 minuters kraftfull bibehållen sugförmåga. Den 40% större behållaren betyder också färre avbrott.",
  "<h1>Avancerad filtrering</h1>",
  "Avancerad filtrering säkerställer att dammsugaren släpper ut renare luft och tömningssystemet 'point and shoot' möjliggör en mer hygienisk metod för att tömma behållaren. Inkluderar åtta verktyg och tillbehör för grundlig rengöring var som helst i hemmet.",
  " Läs mer <i class='fas fa-info-circle'></i>",
  " Lägg till i varukorg <i class='fas fa-cart-plus'></i>",
  8,
  "powerfull",
  1,
  "",
  false
);

export let r1 = new Vacuum(
  "Dyson 360 Heurist™ robot 1",
  3199,
  "url(../assets/Dysoncyclonev10_productpage.png)",
  "<img src='../assets/Robot-Dyson-360-Heurist™-robot-1.png' alt='Bild på en dammsugaren' width='200' height='250'/>",
  "<h2>Dyson 360 Heurist™ robot 1</h2>",
  "<span>Byggt för djup rengöring, överallt. Upp till 60 minuter körtid.</span>",
  "<h1>Dyson 360 Heurist™ robot 1</h1>",
  "<h1>Oslagbar prestanda</h1>",
  "Dyson Cyclone V10 Absolute kommer med upp till 60 minuters kraftfull bibehållen sugförmåga. Den 40% större behållaren betyder också färre avbrott.",
  "<h1>Avancerad filtrering</h1>",
  "Avancerad filtrering säkerställer att dammsugaren släpper ut renare luft och tömningssystemet 'point and shoot' möjliggör en mer hygienisk metod för att tömma behållaren. Inkluderar åtta verktyg och tillbehör för grundlig rengöring var som helst i hemmet.",
  " Läs mer <i class='fas fa-info-circle'></i>",
  " Lägg till i varukorg <i class='fas fa-cart-plus'></i>",
  9,
  "robot",
  1,
  "",
  false
);
export let r2 = new Vacuum(
  "Dyson 360 Heurist™ robot 2",
  3999,
  "url(../assets/Dysoncyclonev10_productpage.png)",
  "<img src='../assets/Robot-Dyson-360-Heurist™-robot-2.png'' alt='Bild på en dammsugaren' width='200' height='250'/>",
  "<h2>Dyson 360 Heurist™ robot 2</h2>",
  "<span>Byggt för djup rengöring, överallt. Upp till 60 minuter körtid.</span>",
  "<h1>Dyson 360 Heurist™ robot 2</h1>",
  "<h1>Oslagbar prestanda</h1>",
  "Dyson Cyclone V10 Absolute kommer med upp till 60 minuters kraftfull bibehållen sugförmåga. Den 40% större behållaren betyder också färre avbrott.",
  "<h1>Avancerad filtrering</h1>",
  "Avancerad filtrering säkerställer att dammsugaren släpper ut renare luft och tömningssystemet 'point and shoot' möjliggör en mer hygienisk metod för att tömma behållaren. Inkluderar åtta verktyg och tillbehör för grundlig rengöring var som helst i hemmet.",
  " Läs mer <i class='fas fa-info-circle'></i>",
  " Lägg till i varukorg <i class='fas fa-cart-plus'></i>",
  10,
  "robot",
  1,
  "",
  false
);
export let r3 = new Vacuum(
  "Dyson 360 Heurist™ robot 3",
  4199,
  "url(../assets/Dysoncyclonev10_productpage.png)",
  "<img src='../assets/Robot-Dyson-360-Heurist™-robot-3.png'' alt='Bild på en dammsugaren' width='200' height='250'/>",
  "<h2>Dyson 360 Heurist™ robot 3</h2>",
  "<span>Byggt för djup rengöring, överallt. Upp till 60 minuter körtid.</span>",
  "<h1>Dyson 360 Heurist™ robot 3</h1>",
  "<h1>Oslagbar prestanda</h1>",
  "Dyson Cyclone V10 Absolute kommer med upp till 60 minuters kraftfull bibehållen sugförmåga. Den 40% större behållaren betyder också färre avbrott.",
  "<h1>Avancerad filtrering</h1>",
  "Avancerad filtrering säkerställer att dammsugaren släpper ut renare luft och tömningssystemet 'point and shoot' möjliggör en mer hygienisk metod för att tömma behållaren. Inkluderar åtta verktyg och tillbehör för grundlig rengöring var som helst i hemmet.",
  " Läs mer <i class='fas fa-info-circle'></i>",
  " Lägg till i varukorg <i class='fas fa-cart-plus'></i>",
  11,
  "robot",
  1,
  "",
  false
);
export let r4 = new Vacuum(
  "Dyson 360 Heurist™ robot 4",
  4999,
  "url(../assets/Dysoncyclonev10_productpage.png)",
  "<img src='../assets/Robot-Dyson-360-Heurist™-robot-4.png'' alt='Bild på en dammsugaren' width='200' height='250'/>",
  "<h2>Dyson 360 Heurist™ robot 4</h2>",
  "<span>Byggt för djup rengöring, överallt. Upp till 60 minuter körtid.</span>",
  "<h1>Dyson 360 Heurist™ robot 4</h1>",
  "<h1>Oslagbar prestanda</h1>",
  "Dyson Cyclone V10 Absolute kommer med upp till 60 minuters kraftfull bibehållen sugförmåga. Den 40% större behållaren betyder också färre avbrott.",
  "<h1>Avancerad filtrering</h1>",
  "Avancerad filtrering säkerställer att dammsugaren släpper ut renare luft och tömningssystemet 'point and shoot' möjliggör en mer hygienisk metod för att tömma behållaren. Inkluderar åtta verktyg och tillbehör för grundlig rengöring var som helst i hemmet.",
  " Läs mer <i class='fas fa-info-circle'></i>",
  " Lägg till i varukorg <i class='fas fa-cart-plus'></i>",
  12,
  "robot",
  1,
  "",
  false
);
